application: remont-cottage
version: 1
api_version: 1
runtime: python

default_expiration: "300d"

handlers:
- url: (.*)/
  static_files: static\1/index.html
  upload: static/index.html

- url: /
  static_dir: static